import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./header";
import Services from "./services";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tutor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
      <Header id="header"></Header>
      <Services id="service"></Services>
      {/* </main> */}

      <footer className={styles.footer}></footer>
    </div>
  );
}
